
services:
  backend:
    build:
      context: ./backend
    container_name: nutritrack-backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    depends_on:
      - mongo
    networks:
      - nutritrack-net

  mongo:
    image: mongo:latest
    container_name: nutritrack-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - nutritrack-net

volumes:
  mongo_data:

networks:
  nutritrack-net:
    driver: bridge
