version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: nutritrack-backend
    ports:
      - "80:5000"  # Expose to public on port 80 (HTTP)
    env_file:
      - ./backend/.env
    networks:
      - nutritrack-net

networks:
  nutritrack-net:
    driver: bridge
